## Brute
+   scipy.optimize.brute(func, ranges, args=(), Ns=20, full_output=0, finish=<function fmin at 0x49e4e60>, disp=False)

func : callable

+   The objective function to be minimized. Must be in the form f(x, *args), where x is the argument in the form of a 1-D array and args is a tuple of any additional fixed parameters needed to completely specify the function.

ranges : tuple

+   Each component of the ranges tuple must be either a “slice object” or a range tuple of the form (low, high). The program uses these to create the grid of points on which the objective function will be computed. See Note 2 for more detail.

args : tuple, optional

+   Any additional fixed parameters needed to completely specify the function.

Ns : int, optional

+   Number of grid points along the axes, if not otherwise specified. See Note2.

full_output : bool, optional

+   If True, return the evaluation grid and the objective function’s values on it.

finish : callable, optional

+   An optimization function that is called with the result of brute force minimization as initial guess. finish should take the initial guess as positional argument, and take args, full_output and disp as keyword arguments. Use None if no “polishing” function is to be used. See Notes for more details.

disp : bool, optional

+   Set to True to print convergence messages.

In [3]:
from scipy import optimize
import numpy as np

In [4]:
params =(2,3,7,8,9,10,44,-1,2,26,1,-2,0.5)

## function 1
def f1(z,*params):
    x,y =z
    a,b,c,d,e,f,g,h,i,j,k,l, scale = params
    return (a * x**2 + b * x * y + c * y**2 + d*x + e*y + f)

## function 2
def f2(z, *params):
    x, y = z
    a, b, c, d, e, f, g, h, i, j, k, l, scale = params
    return (-g*np.exp(-((x-h)**2 + (y-i)**2) / scale))

## function 3
def f3(z, *params):
    x, y = z
    a, b, c, d, e, f, g, h, i, j, k, l, scale = params
    return (-j*np.exp(-((x-k)**2 + (y-l)**2) / scale))

## Global function
def f(z, *params):
    return f1(z, *params) + f2(z, *params) + f3(z, *params)

In [5]:
rranges = (slice(-4, 4, 0.25), slice(-4, 4, 0.25))
rranges

(slice(-4, 4, 0.25), slice(-4, 4, 0.25))

In [9]:
resbrute = optimize.brute(
    f,
    rranges,
    args= params,
    full_output=True,
    finish= optimize.fmin
)

In [10]:
resbrute

(array([-1.05665192,  1.80834843]),
 -3.4085818767996527,
 array([[[-4.  , -4.  , -4.  , ..., -4.  , -4.  , -4.  ],
         [-3.75, -3.75, -3.75, ..., -3.75, -3.75, -3.75],
         [-3.5 , -3.5 , -3.5 , ..., -3.5 , -3.5 , -3.5 ],
         ...,
         [ 3.25,  3.25,  3.25, ...,  3.25,  3.25,  3.25],
         [ 3.5 ,  3.5 ,  3.5 , ...,  3.5 ,  3.5 ,  3.5 ],
         [ 3.75,  3.75,  3.75, ...,  3.75,  3.75,  3.75]],
 
        [[-4.  , -3.75, -3.5 , ...,  3.25,  3.5 ,  3.75],
         [-4.  , -3.75, -3.5 , ...,  3.25,  3.5 ,  3.75],
         [-4.  , -3.75, -3.5 , ...,  3.25,  3.5 ,  3.75],
         ...,
         [-4.  , -3.75, -3.5 , ...,  3.25,  3.5 ,  3.75],
         [-4.  , -3.75, -3.5 , ...,  3.25,  3.5 ,  3.75],
         [-4.  , -3.75, -3.5 , ...,  3.25,  3.5 ,  3.75]]]),
 array([[134.        , 119.6875    , 106.25      , ...,  74.18749997,
          85.24999999,  97.1875    ],
        [129.125     , 115.        , 101.75      , ...,  74.74999948,
          85.99999987,  98.1249999

### global minimum

In [11]:
resbrute[0]

array([-1.05665192,  1.80834843])

### function value at global minimum

In [12]:
resbrute[1]

-3.4085818767996527

In [13]:
def x():
    return x^2

In [29]:
rranges = (slice(-100, 100,0.25),)

In [30]:
resbrute = optimize.brute(
    x,
    rranges,
    full_output=True,
    finish= optimize.fmin
)

TypeError: x() takes 0 positional arguments but 1 was given